### ISSUE TITLE
Interpret file output

### ISSUE THREAD

**Issue by dcecile** [tacit-lang/tacit-gen3-python#1]
_For tacit-lang/tacit#1_

#### Syntax tree

- Block
  - Statements
    - Expression
      - Terms
      - Block

#### Execution

Stack machine implemented in Python, everything works on a "frame stack".

- New frames pushed when a block or expression runs
- Frames include...
  - Expression stack (can be shared)
  - Environment (linked to parent)
  - Continuation (next term or statement to evaluate)
- Old frames popped when returning
- Tail calls happen by popping before pushing the tail call

### Tasks
- [x] Design rough interpreter structure
- [x] Interpret numeric literals
- [x] Connect interpreter REPL
- [x] Connect interpreter runner
- [x] Interpret identifiers
- [x] Set up test framework
- [x] Interpret hex literals
- [x] Interpret method calls
- [x] Interpret blob create & add (implement via [bytearray](https://docs.python.org/3/library/stdtypes.html#bytearray))
- [x] Find out how to serialize [NumPy data types](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.dtypes.html)
- [x] Interpret numeric suffixes (implement via [NumPy](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html))
- [x] Interpret comments
- [x] Interpret file output to `cout`
- [x] Interpret assignment statements
- [x] Interpret method definition & calls
- [x] Interpret `main` method
- [x] Interpret cat blob and blob

**Comment by dcecile** [comment]
Instances of `numpy.number` (e.g. `numpy.int32`, `numpy.uint8`) all have a `tobytes` method (very lightly documented at [`numpy.generic`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.generic.html))

**Comment by dcecile** [comment]
Done, ELF executable output interpreted

(Blob add and cat written with roughly-correct performance semantics, but side effect is currently observable)
