### ISSUE TITLE
Set up Python environment

### ISSUE THREAD

**Issue by dcecile** [tacit-lang/tacit-gen3-python#2]
### Requirements

- Low latency
- No formatting decisions
- Python 3 best practices
- Commit important VS Code config to source control

### Tasks

- [x] Set up Pipenv
- [x] Set up Pipenv + Zsh integration
- [x] Set up continuous Pytest testing
- [x] Set up a simple parser with Parsita
- [x] Switch away from Pipenv
- [x] [Separate Python environment directory from workspace VS Code config](https://github.com/Microsoft/vscode-python/issues/2125#issuecomment-403928218)
- [x] Set up [Black](https://github.com/ambv/black)
- [x] Set up [isort](https://readthedocs.org/projects/isort/)
- [x] Set up [Flake8](https://github.com/ambv/black/blob/master/.flake8)
- [x] Set up [VS Code Black](https://code.visualstudio.com/docs/python/editing#_formatting)
- [x] Set up [VS Code Flake8](https://code.visualstudio.com/docs/python/linting#_flake8)
- [x] Set up [VS Code isort](https://code.visualstudio.com/docs/python/editing#_sort-imports)
- [x] Set up [VS Code REPL exec](https://code.visualstudio.com/docs/python/editing#_run-selectionline-in-terminal-repl)
- [x] Set up [VS Code IntelliCode](https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode)
- [x] Set up [VS Code Python snippets](https://github.com/Microsoft/vscode-python/blob/master/snippets/python.json)
- [x] Set up [VS Code Python refactoring](https://code.visualstudio.com/docs/python/editing#_refactoring)
- [x] Set up [VS Code extra settings](https://code.visualstudio.com/docs/python/settings-reference)
- [x] Commit VS Code config (including extensions)

**Comment by dcecile** [comment]
Good initial setup
